spring.application.name=session-generator

spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# Большие файлы не загружаем — пути вводятся вручную
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.port=8090
